# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_text.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 316)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(5, 11, 641, 181))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setUndoRedoEnabled(True)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 280, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowserLastRecogn = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserLastRecogn.setGeometry(QtCore.QRect(5, 199, 641, 71))
        self.textBrowserLastRecogn.setReadOnly(True)
        self.textBrowserLastRecogn.setObjectName("textBrowserLastRecogn")
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setGeometry(QtCore.QRect(7, 280, 201, 23))
        self.label_status.setObjectName("label_status")
        self.pushButtonBack = QtWidgets.QPushButton(Dialog)
        self.pushButtonBack.setGeometry(QtCore.QRect(440, 280, 61, 23))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonForward = QtWidgets.QPushButton(Dialog)
        self.pushButtonForward.setGeometry(QtCore.QRect(500, 280, 61, 23))
        self.pushButtonForward.setObjectName("pushButtonForward")
        self.pushButtonStopRec = QtWidgets.QPushButton(Dialog)
        self.pushButtonStopRec.setGeometry(QtCore.QRect(160, 280, 141, 23))
        self.pushButtonStopRec.setObjectName("pushButtonStopRec")
        self.pushButtonHelp = QtWidgets.QPushButton(Dialog)
        self.pushButtonHelp.setGeometry(QtCore.QRect(580, 280, 61, 23))
        self.pushButtonHelp.setObjectName("pushButtonHelp")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование текста"))
        self.textBrowser.setPlaceholderText(_translate("Dialog", "result text"))
        self.pushButton.setText(_translate("Dialog", "Копировать в буфер"))
        self.label_status.setText(_translate("Dialog", "Статус"))
        self.pushButtonBack.setText(_translate("Dialog", "Назад"))
        self.pushButtonForward.setText(_translate("Dialog", "Вперед"))
        self.pushButtonStopRec.setText(_translate("Dialog", "Начать запись"))
        self.pushButtonHelp.setText(_translate("Dialog", "Помощь"))
